name = "json-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2014-2024, Jacob Williams"
license = "BSD"
description = "A Modern Fortran JSON API"
homepage = "https://github.com/jacobwilliams/json-fortran"
categories = ["io"]
keywords = ["JSON"]

[build]
external-modules = "ifcore"
auto-executables = true
auto-examples = true
auto-tests = true

[library]
source-dir = "src"
