name = "json-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2014-2024, Jacob Williams"
license = "BSD"
description = "A Modern Fortran JSON API"
homepage = "https://github.com/jacobwilliams/json-fortran"
categories = ["io"]
keywords = ["JSON"]

[build]
external-modules = "ifcore"

[library]
source-dir = "src"

[[test]]
name       = "jf_test_01"
source-dir = "src/tests"
main       = "jf_test_01.F90"

[[test]]
name       = "jf_test_02"
source-dir = "src/tests"
main       = "jf_test_02.F90"

[[test]]
name       = "jf_test_03"
source-dir = "src/tests"
main       = "jf_test_03.F90"

[[test]]
name       = "jf_test_04"
source-dir = "src/tests"
main       = "jf_test_04.F90"

[[test]]
name       = "jf_test_05"
source-dir = "src/tests"
main       = "jf_test_05.F90"

[[test]]
name       = "jf_test_06"
source-dir = "src/tests"
main       = "jf_test_06.F90"

[[test]]
name       = "jf_test_07"
source-dir = "src/tests"
main       = "jf_test_07.F90"

[[test]]
name       = "jf_test_08"
source-dir = "src/tests"
main       = "jf_test_08.F90"

[[test]]
name       = "jf_test_09"
source-dir = "src/tests"
main       = "jf_test_09.F90"

[[test]]
name       = "jf_test_10"
source-dir = "src/tests"
main       = "jf_test_10.F90"

[[test]]
name       = "jf_test_11"
source-dir = "src/tests"
main       = "jf_test_11.F90"

[[test]]
name       = "jf_test_12"
source-dir = "src/tests"
main       = "jf_test_12.F90"

[[test]]
name       = "jf_test_13"
source-dir = "src/tests"
main       = "jf_test_13.F90"

[[test]]
name       = "jf_test_14"
source-dir = "src/tests"
main       = "jf_test_14.F90"

[[test]]
name       = "jf_test_15"
source-dir = "src/tests"
main       = "jf_test_15.F90"

[[test]]
name       = "jf_test_16"
source-dir = "src/tests"
main       = "jf_test_16.F90"

[[test]]
name       = "jf_test_17"
source-dir = "src/tests"
main       = "jf_test_17.F90"

[[test]]
name       = "jf_test_18"
source-dir = "src/tests"
main       = "jf_test_18.F90"

[[test]]
name       = "jf_test_19"
source-dir = "src/tests"
main       = "jf_test_19.F90"

[[test]]
name       = "jf_test_20"
source-dir = "src/tests"
main       = "jf_test_20.F90"

[[test]]
name       = "jf_test_21"
source-dir = "src/tests"
main       = "jf_test_21.F90"

[[test]]
name       = "jf_test_22"
source-dir = "src/tests"
main       = "jf_test_22.F90"

[[test]]
name       = "jf_test_23"
source-dir = "src/tests"
main       = "jf_test_23.F90"

[[test]]
name       = "jf_test_24"
source-dir = "src/tests"
main       = "jf_test_24.F90"

[[test]]
name       = "jf_test_25"
source-dir = "src/tests"
main       = "jf_test_25.F90"

[[test]]
name       = "jf_test_26"
source-dir = "src/tests"
main       = "jf_test_26.F90"

[[test]]
name       = "jf_test_27"
source-dir = "src/tests"
main       = "jf_test_27.F90"

[[test]]
name       = "jf_test_28"
source-dir = "src/tests"
main       = "jf_test_28.F90"

[[test]]
name       = "jf_test_29"
source-dir = "src/tests"
main       = "jf_test_29.F90"

[[test]]
name       = "jf_test_30"
source-dir = "src/tests"
main       = "jf_test_30.F90"

[[test]]
name       = "jf_test_31"
source-dir = "src/tests"
main       = "jf_test_31.F90"

[[test]]
name       = "jf_test_32"
source-dir = "src/tests"
main       = "jf_test_32.F90"

[[test]]
name       = "jf_test_33"
source-dir = "src/tests"
main       = "jf_test_33.F90"

[[test]]
name       = "jf_test_34"
source-dir = "src/tests"
main       = "jf_test_34.F90"

[[test]]
name       = "jf_test_35"
source-dir = "src/tests"
main       = "jf_test_35.F90"

[[test]]
name       = "jf_test_36"
source-dir = "src/tests"
main       = "jf_test_36.F90"

[[test]]
name       = "jf_test_37"
source-dir = "src/tests"
main       = "jf_test_37.F90"

[[test]]
name       = "jf_test_38"
source-dir = "src/tests"
main       = "jf_test_38.F90"

[[test]]
name       = "jf_test_39"
source-dir = "src/tests"
main       = "jf_test_39.F90"

[[test]]
name       = "jf_test_40"
source-dir = "src/tests"
main       = "jf_test_40.F90"

[[test]]
name       = "jf_test_41"
source-dir = "src/tests"
main       = "jf_test_41.F90"

[[test]]
name       = "jf_test_42"
source-dir = "src/tests"
main       = "jf_test_42.F90"

[[test]]
name       = "jf_test_43"
source-dir = "src/tests"
main       = "jf_test_43.F90"

[[test]]
name       = "jf_test_44"
source-dir = "src/tests"
main       = "jf_test_44.F90"

[[test]]
name       = "jf_test_45"
source-dir = "src/tests"
main       = "jf_test_45.F90"

[[test]]
name       = "jf_test_46"
source-dir = "src/tests"
main       = "jf_test_46.F90"

[[test]]
name       = "jf_test_47"
source-dir = "src/tests"
main       = "jf_test_47.F90"

[[test]]
name       = "jf_test_48"
source-dir = "src/tests"
main       = "jf_test_48.F90"

[[test]]
name       = "jf_test_49"
source-dir = "src/tests"
main       = "jf_test_49.F90"

[[test]]
name       = "jf_test_50"
source-dir = "src/tests"
main       = "jf_test_50.F90"

[[test]]
name       = "jf_test_51"
source-dir = "src/tests"
main       = "jf_test_51.F90"

[[test]]
name       = "jf_test_52"
source-dir = "src/tests"
main       = "jf_test_52.F90"

[[test]]
name       = "jf_test_53"
source-dir = "src/tests"
main       = "jf_test_53.F90"